### ISSUE TITLE
Issues with both the Alpha version and the most recent version

### ISSUE THREAD

**Issue by AvoidAtAllCosts** [c0dycode/BL-AutoexecDLL#2]
I'm experiencing issues with both the alpha version of this mod but also the current version of this mod. Your mod itself functions properly for me; it automatically executes my patch.txt file, however... 

(I had issues with BL2 crashing before but that was because 2 mods I was using were incompatible. After removing one of the mods that clashed with the other the crashes were gone, but I still experienced an issue that seemed to be caused by this mod, since this issue was gone after I disabled this mod.)

 If I use your PhysXExtensions.dll I noticed that after ~10 minutes; Zer0's deception (for example) will be infinite, vendors and the inventory wont respond to the cursor any more and whenever I try leaving the area I'm currently in, the game will crash. 

2 weeks ago, you adviced me to use your alpha version instead which indeed doesn't have this issue for me, but instead this version prevents me from launching the game unless I remove your Steam_api.dll file from Win32, change Steam_api_org.dll back to Steam_api.dll, launch BL2, exit BL2, copy and paste your Steam_api.dll and rename the original one. I have to redo this every time I launch BL2.

I wondered if the infinite deception bug may had been caused by a mod I used so I tested your mod with an empty patch.txt file and the bug still happened. I also don't run any other programs for BL2 besides the BL2 mod manager (I hex edited BL2 via the manager) and ReShade. Any idea how I can fix (one of these 2) issues? Your mod is really convenient so it'd be really nice if it wouldn't cause these issues for me. Thanks!

**Comment by c0dycode** [comment]
Yeah, I'm still looking into those issues. The only change from the newer one to the alpha version, is additional error-checking so the game is less likely to crash. However this seem to have introduce some of those weird issues. Which I, unfortunately, still can not reproduce. So this makes it pretty difficult for me.

You don't have to do all that renaming to fix the launch issue via. steam. 

Usually it should fix itself after you've launched the game via the Borderlans2.exe directly. It should work with steam fine afterwards.

You can also try to rename it to "ATIMGPUD.dll" and steam_api_org.dll back to steam_api.dll.

That seems to fix the steam-launching issue at least.

**Comment by c0dycode** [comment]
Have you tried the new PluginTest version?
