### ISSUE TITLE
Occasional hang when saving

### ISSUE THREAD

**Issue by Akaitatsu** [c0dycode/BL-AutoexecDLL#4]
I have had the game save hang a few times since I added the autoexec patch. I can move around and play to some degree. However, the save icon stays up continuously, I can't click on inventory items, and the game hangs completely if I try to save and quit (alt+F4 kills it).

I am playing BL2 via Steam on Windows 10 using the AutoexecNoGravityMode dll.

I will play for a while without the autoexec to make sure it isn't a corrupt save or something like that.

Let me know what logs, memory dumps, etc. that I can gather. I am pretty technical but will probably need instructions for things like memory dumps.

**Comment by c0dycode** [comment]
Those issues have been reported for the old outdated autoexec, not for the new one afaik.

Use the Plugin-version instead. That should fix those issues.

**Comment by Akaitatsu** [comment]
Sorry, I apparently misread the instructions. I'm trying the plugin version now.

**Comment by Akaitatsu** [comment]
I have played two decent sessions since switching to the plugin version and no problems.

You might want to pull the older version to prevent more dummies like myself from downloading the first thing they see. :)

**Comment by c0dycode** [comment]
Thanks for the feedback :)

I'll do that 👍 Let me know if you run into any other issues with it. Until then, enjoy 😃
