### ISSUE TITLE
Autoexec.txt does not exist in the Binaries folder!

### ISSUE THREAD

**Issue by AlexKMB** [c0dycode/BL-AutoexecDLL#6]
Hi,

Just followed your instructions but nothing seems to work for me, i don't know where the problem is, when i launch the game nothing happen and a .txt is create in my folder with mention " autoexec.txt doesn't exist in the Binaries folder ", i send you a puush file to see the path of my set up

http://puu.sh/D77Ts/fddbed557d.png

The ddraw.dll is in the Win32 folder by the way (http://puu.sh/D77UH/43f00a0071.png)

Thanks

**Comment by c0dycode** [comment]
Hm, it seems replying to the e-mail notification did not do what I expected it do 😆 

Just to make sure:

Hey,


what's the content of your autoexec.txt?

Delete the autoexec.log file and try again. If it creates the same file with "autoexec.txt does not exist in the Binaries folder!" inside again, then it can't find the file for some reason.

**Comment by AlexKMB** [comment]
Hey,

It's ok, was my bad .. I'm dumb as fuck, just rename my patch text file to patch.txt so is name was patch.txt.txt ........

So it was my bad, not your ! Sorry for that !

**Comment by c0dycode** [comment]
No worries :)
Glad you figured it out 👍
