### ISSUE TITLE
Autoexec not working properly (with or without the UHD update)

### ISSUE THREAD

**Issue by Liberage** [c0dycode/BL-AutoexecDLL#8]
Hey, i'm currently having issues with your autoexec.
It just... won't work...
I've followed every instruction correctly, and fixed my Patch name in the autoexec.txt ([like in this issue](https://github.com/c0dycode/BL-AutoexecDLL/issues/6)).
All the directories are correct.
I've got some questions though; does the "autoexec.txt" need to be named exactly like that? Or the .txt is just the extension? (i.e autoexec.txt or autoexec [but with only the extension, not an actual txt in the name])
I also had the older chromium based autoexec, is it possible that there are leftover files? If so how do i remove them?

**Comment by c0dycode** [comment]
The ".txt" is just the extension :)
If you remove it and the "Type" in your explorer is still "Textdocument" then it's named correctly.
You can easily check that. If your Patchfile is called "Patch" but you need to enter "Patch.txt" then just name it "Autoexec". 

Same goes for the "Online=" and "Offline=" settings.
If you need to type "exec Patch.txt" then the setting also needs to be "Online=exec Patch.txt" for example.

The AutoHotkey version shouldn't matter. That one used "autoexec.ini" if I remember correctly and only runs if you start it manually.

See if that fixes the issue :)

**Comment by Liberage** [comment]
Thanks for the reply!
So before this issue, i tried uninstalling the UHD, and tinkering a lil bit, but every attempt had no success, however while i was trying to get the autoexec to work, i tried using a hex editor to properly edit values so that the exec could read them. This was an accidental lucky discovery, since i discovered that even if you uninstall the UHD, your game remains patched as UHD! And when i uninstalled the UHD, i was using the normal one. After one final attempt, and after realizing all this, i swapped the two, and it works! I'm so glad, because i was so frustrated, and also everytime having to enter that command... ugh...
Thank you so much!
