### ISSUE TITLE
The latest update to the BL2 build doesnt do anything

### ISSUE THREAD

**Issue by brunocar** [c0dycode/BL-AutoexecDLL#9]
I installed the latest build, the previous one crashed the game, this one doesnt do anything, i can load the patch manually, but the intro isnt skipped and the patch isnt autoloaded

**Comment by c0dycode** [comment]
Hm, maybe you need to update the vc_redistx86 update. 🤔 

https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by brunocar** [comment]
nope, that didnt fix it, i had the latest one anyways.

**Comment by c0dycode** [comment]
Can you post your "Autoexec.txt"?

**Comment by brunocar** [comment]
> Online=exec Patch.txt
> Offline=exec PatchOffline.txt
> Fastmode=true
> ForceOfflineHotfixes=false

thats all there is in the file, i havent changed it since the last update

as for the older version, nope, it crashed the entire game, didnt even open a window, i can send the crash dump if you want, i didnt delete ddraw.dll to fix it, i removed the autoexec plugin from the folder, that said, i copied the new ddraw.dll and the new plugin folder and overwrote it, so i doubt any old files beyond Autoexec.txt were left

**Comment by c0dycode** [comment]
Okay, I had somebody else test this. Including me, we are the only people I know off so far that used/tested this version. It worked for him. Can you double check that everything is installed as it should be?

To verify that the PluginLoader is installed correctly and loaded by the game, you could use the bundled Example Application from the "CommandInjector.zip" https://github.com/c0dycode/BL-CommandInjector/blob/master/CommandInjector.zip

**Comment by brunocar** [comment]
i've tried that and it works, i sent a say command through the example app and it worked, it must be related to the new version of the autoexec plugin

**Comment by c0dycode** [comment]
Can you post a screenshot of your "Binaries" folder? :)

**Comment by brunocar** [comment]
![Annotation 2019-06-11 121400](https://user-images.githubusercontent.com/14931359/59284407-94947c00-8c42-11e9-80c2-76a9fd44a50b.png)

thats the screenshot

**Comment by c0dycode** [comment]
And you do not have a "Autoexec.log" in the Plugins-folder I assume?

**Comment by brunocar** [comment]
not a log file, but there is a dump file under that name, want me to send it?

**Comment by c0dycode** [comment]
Is the date from after you downloaded this new version? If so, then yeah. You can attach it :) Otherwise it won't be of use :/

**Comment by brunocar** [comment]
nope, i think its the crash log from the last version, any other ideas?

**Comment by NyanDynamiX** [comment]
I'm having the exact problem with the current version as well. Previous versions would crash and leave a dmp file but the current version doesn't crash at all (I've tried removing and adding '-uhd' to the dll but none had a response) to even leave a dmp file, I'm no programmer but it seems as if the game isn't recognizing (or executing) the autoexec.dll/autoexec.txt at all (in my case atleast). I've tried the CommandInjector app and it tells me that my plugins is installed but the commandinjector isnt loading into the game. Normally inputting 'exec patch.txt' into the ingame console works as it should. Also note that I have the Handsome collection but I'm not using the UHD DLC.

**Comment by c0dycode** [comment]
Hm, not really :/ You can give this one a try though.
[autoexec-UHD.zip](https://github.com/c0dycode/BL-AutoexecDLL/files/3277302/autoexec-UHD.zip)

If this doesn't help either, I'll try to find a few more testers. Other than that, the only reasons I know off that'd cause the same behavior is if the DLL is not being loaded at all, if the autoexec.txt does not exist or if the autoexec.txt uses a different encoding than the ones highlighted here:
![image](https://user-images.githubusercontent.com/3851319/59286323-cd971580-8c6f-11e9-9564-7b8a391338e8.png)

**Comment by brunocar** [comment]
according to notepad++ my file is encoded in normal UTF-8, i'll try changing the encoding

**Comment by c0dycode** [comment]
That should be fine then :/
I've just tested all of those and it only failed to "autoexec" if it was set to one of the two UTF-16

**Comment by brunocar** [comment]
yep, that didnt work, also, that other build you sent shows the same behaviour

**Comment by brunocar** [comment]
i'll try reinstalling the visual c++ redist again and rebooting, maybe that changes something :P

**Comment by c0dycode** [comment]
[autoexec-UHD.zip](https://github.com/c0dycode/BL-AutoexecDLL/files/3277441/autoexec-UHD.zip)
If that doesn't help, try this one. This won't address the issue, but I've added some basic logging.

![image](https://user-images.githubusercontent.com/3851319/59288169-6a0ee700-8c73-11e9-84b4-8476db131ea7.png)

This should ™️ give me a hint about where the issue could be. And if the "Autoexec.log" is not inside the Plugins folder with this one, then the game refuses to load the DLL for some odd reason.

**Comment by brunocar** [comment]
ok, reinstalling the redist didnt work, i'll try that.

**Comment by brunocar** [comment]
i suspect its indeed that the game refuses to load the DLL for whatever reason, no log file, nothing in the console.

**Comment by c0dycode** [comment]
This used to be fixed by the vcredistx86. And the linked one should include 2015, 2017 and 2019. The DLL is compiled for/with 2017, so that should be fine.

There's one other thing you could check/try. Try to right click the DLL, open the properties and see if you can "Unblock" it.

Something like this.
![image](https://user-images.githubusercontent.com/3851319/59289390-426d4e00-8c76-11e9-9422-e3d85b33985f.png)

**Comment by brunocar** [comment]
already thought of that, didnt work

**Comment by c0dycode** [comment]
Damn :/

Here's one more, which logs a few more things and earlier. Maybe it fails somewhere before the previous logging.
[autoexec-UHD.zip](https://github.com/c0dycode/BL-AutoexecDLL/files/3277567/autoexec-UHD.zip)

If this doesn't help either, I'm out of ideas atm :/

**Comment by brunocar** [comment]
that also didnt help, does the fact that the game isnt on the system drive change anything?

**Comment by c0dycode** [comment]
That should not matter. My game is on E:\ instead of C:\ aswell.

So it still does not generate any log in the Plugins folder?

**Comment by brunocar** [comment]
nope, i'll try a couple things and see if it does anything

**Comment by brunocar** [comment]
wait, i just found something, there is a file in the win32 folder called ddraw.txt, it says the following

> Failed to load DLL: D:\SteamLibrary\steamapps\common\Borderlands 2\Binaries\Win32\Plugins\autoexec-UHD.dll with errorcode: 126

**Comment by c0dycode** [comment]
Ohhh, that indeed could be useful.
Does this help? 👀 
[autoexec-UHD.zip](https://github.com/c0dycode/BL-AutoexecDLL/files/3277626/autoexec-UHD.zip)

**Comment by brunocar** [comment]
finally some progress.

ok, so that worked, sorta, the plugin did indeed work and it skipped the title screen and intros, however, it didnt execute the patch, but it did try to, using a command called ne=exec, rather than the usual exec, that failed but it did leave a log on the console.

**Comment by c0dycode** [comment]
Neat, okay. In that case double check the encoding or redo the autoexec.txt.

**Comment by brunocar** [comment]
YEP, that worked, turns out UTF-8 with BOM doesnt work properly unless you change the formating of the text (the "ne=" thing are the 3 last characters of online=) so i reverted to UTF-8 and it worked, closing the issue, thanks for the help!

btw, what did you change to solve the error code?

**Comment by c0dycode** [comment]
Perfect :)
Can you try/confirm this too @NyanDynamiX ?

In the project settings the "Runtime Library" was set to "Multi-threaded Debug DLL (/MDd)".
This seems to work just fine for people that have any kind of development environment that uses the debug versions of those Microsoft "Libraries". Or if you have the debug-version of those installed.

I've switched it now to "Multi-threaded DLL (/MD)" without the Debug and it uses the non-debug microsoft libraries now.

**Comment by NyanDynamiX** [comment]
I will confirm that it now loads normally, patch and all. Thanks for your hard work!

**Comment by c0dycode** [comment]
Perfect :) Thanks for reporting and testing, you two ❤️ 

I'll upload the fixed version then :)
